[helpers]

[default]
depends = []

[default.variables]

[default.files]
"hypr/hyprland.conf" = "~/.config/hypr/hyprland.conf"
"waybar/" = "~/.config/waybar/"
"kitty/" = "~/.config/kitty/"
"nvim/init.vim" = "~/.config/nvim/init.vim"
"bash/bash_profile" = "~/.bash_profile"
"bash/bashrc" = "~/.bashrc"
"bash/inputrc" = "~/.inputrc"
"bash/git-prompt.sh" = "~/.prompt-git.sh"
"tmux.conf" = "~/.tmux.conf"
"launchers/brave-browser.desktop" = "~/.local/share/applications/brave-browser.desktop"
"launchers/obsidian.desktop" = "~/.local/share/applications/obsidian.desktop"
"tofi/config" = "~/.config/tofi/config"


[settings]
default_target_type = "automatic"
