[helpers]

[default]
depends = []

[default.variables]

[default.files]
"hypr/hyprland.conf" = "~/.config/hypr/hyprland.conf"
"waybar/" = "~/.config/waybar/"
"kitty/" = "~/.config/kitty/"
"launchers/brave-browser.desktop" = "~/.local/share/applications/brave-browser.desktop"
"launchers/obsidian.desktop" = "~/.local/share/applications/obsidian.desktop"


[settings]
default_target_type = "automatic"
