[helpers]

[default]
depends = []

[default.variables]

[default.files]
"nvim/init.lua" = "~/.config/nvim/init.lua"
"bash/bash_profile" = "~/.bash_profile"
"bash/bashrc" = "~/.bashrc"
"bash/inputrc" = "~/.inputrc"
"bash/git-prompt.sh" = "~/.prompt-git.sh"
"tmux.conf" = "~/.tmux.conf"
"alacritty/alacritty.toml" = "~/.config/alacritty/alacritty.toml"
"SpeedCrunch/SpeedCrunch.ini" = "~/.config/SpeedCrunch/SpeedCrunch.ini"
"profile" = "~/.profile"
"noctalia" = "~/.config/noctalia"
"launchers" = "~/.local/share/applications"
"niri" = "~/.config/niri"

[settings]
default_target_type = "automatic"
