[helpers]

[default]
depends = []

[default.variables]

[default.files]
"hypr/hyprland.conf" = "~/.config/hypr/hyprland.conf"
"waybar/" = "~/.config/waybar/"

[settings]
default_target_type = "automatic"
