# .bash_profile
export XDG_RUNTIME_DIR=$(ls -d /tmp/service-$USER.???* 2>/dev/null || mktemp -d /tmp/service-$USER.XXX | tee >(xargs chmod 0700))
#if [[ -z "$XDG_RUNTIME_DIR" ]]; then
#  export XDG_RUNTIME_DIR="/run/user/$(id -u)"
#  mkdir -p "$XDG_RUNTIME_DIR"
#  chmod 700 "$XDG_RUNTIME_DIR"
#fi

if [[ $(tty) == /dev/tty1 ]]; then
  brightnessctl -q -d intel_backlight set 40%
  brightnessctl -q -d chromeos::kbd_backlight set 100%
  exec dbus-run-session niri --session
fi

# Get the aliases and functions
[ -f $HOME/.bashrc ] && . $HOME/.bashrc
